name: GitHub Actions  on Powershell
on: [push]
jobs:
  Powershell-GitHub-Actions:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: check repository
        run: powershell ls
      - name: run powershell code
        shell: pwsh
        run: powershell .\GITACTIONS\power.ps1

      