name: GitHub Actions  on Powershell
on: [push]
jobs:
  Powershell-GitHub-Actions:
    runs-on: windows-2019
    steps:
      - run: powershell dir
      - run: powershell pwd
      - run:  Powershell .\power.ps1